[user]
name = "Sebastian Vilhelm Juhl"
email = "seb.vilhelm@gmail.com"

[ui]
merge-editor = ["nvim", "-d", "-O", "$left", "$base", "$right"]
default-command = "log"

[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]
