[user]
name = "Sebastian Vilhelm Juhl"
email = "seb.vilhelm@gmail.com"

[signing]
sign-all = true
backend = "ssh"

[ui]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
default-command = "log"

[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]
